# Base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY ../../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the FastAPI code
COPY ../../api_service ./api_service
COPY ../../ml_model ./ml_model
COPY ../../config ./config

# Expose the port FastAPI will run on
EXPOSE 8000

# Run the API
CMD ["uvicorn", "api_service.main:app", "--host", "0.0.0.0", "--port", "8000"]
